### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by ejolly** [wrjlewis/notion-search-alfred-workflow#1]
Just saw this on reddit and wanted to say thanks as an Alfred user!

In case other folks run into this, I found that there were several cookies listed in my request header but the key one is `token_v2=...` and including the `token_v2=` in the workflow variable was required, whereas the workspace id could be pasted as is.

**Comment by wrjlewis** [comment]
I've updated the readme with a couple of screenshots to make this more clear. Thanks!
