### ISSUE TITLE
after last plan update extension don't work

### ISSUE THREAD

**Issue by macgyverkam** [wrjlewis/notion-search-alfred-workflow#10]

**Comment by macgyverkam** [comment]
I think some of data from cookies is now different.

**Comment by carlosflorencio** [comment]
Works for me, you may need to get a new cookie.

**Comment by macgyverkam** [comment]
Correct, new cookie, this was it. Thanks!

**Comment by wrjlewis** [comment]
Closing, as this is now resolved.
