### ISSUE TITLE
Cookie doesn’t seem to work for me

### ISSUE THREAD

**Issue by mvdesign** [wrjlewis/notion-search-alfred-workflow#2]
Hi there,

This seems like a handy idea. I’ve just spent a significant amount of time trying to get it to work, and I still have yet to get more than "No results - go to Notion homepage."

I really feel like I'm using the proper "search" cookie (See below... I cropped it to a point where I don't think there's anything personally identifiable, but you get the point):

<img width="326" alt="Cookie?" src="https://user-images.githubusercontent.com/730876/75221299-85714200-576f-11ea-8837-6ee621182432.png">

I've tried grabbing it from Safari and Chrome and Firefox (my default browser). And none of them work. 

So I'm a little stumped. Any ideas about what I might be doing wrong?

Thanks for your work on this and for making it available.

**Comment by FelixLisczyk** [comment]
Yes, this is the correct value. Although my cookie contains a parameter `_ga` before `ajs_anonymous_id`.

* Did you copy the complete value without the `cookie:` prefix?
* Did you also insert your `spaceId` into the workflow?

**Comment by pbajaria** [comment]
If you look at the cookie it has many items that are separated by ";".  The only item that you need  from the cookie is the following:
token_v2=XXXXXXXX

Copy this value in the "cookie" workflow parameter

**Comment by mvdesign** [comment]
Thanks for your responses and for trying to think through this with me.

@FelixII 
>     * Did you copy the complete value without the `cookie:` prefix?
>     * Did you also insert your `spaceId` into the workflow?

I did both of those things. I've triple checked the `spaceId`. It still doesn't work for me.

@pbajaria 
> If you look at the cookie it has many items that are separated by ";". The only item that you need from the cookie is the following:
> token_v2=XXXXXXXX
> 
> Copy this value in the "cookie" workflow parameter

I've tried `token_v2=XXXXXXXX` and `XXXXXXXX` but neither works for me. I've also noticed that the token_v2 changes from browser to browser and/or from session to session.

I'm still stumped by this. If I don't get it to work, that's not a big deal. But it seems like a cool integration.

**Comment by wrjlewis** [comment]
Hi @mvdesign ,

Is this still not working for you?

**Comment by mvdesign** [comment]
Thanks for checking in. Honestly, I got pretty busy, and with working and parenting from home, this got pushed waaaaay down my to-do list. If you feel like closing this just to keep things tidy, that's fine with me. I'm not sure if and when I'll try again, but I could always reopen it when I do.

**Comment by wrjlewis** [comment]
Ok, well when you're ready I'd be happy to show you how I've got it to work for me and compare to how you have it done. I get my cookie from the 'search' request which is triggered by typing into the quick find bar, and I just copy the whole value. Thanks.

**Comment by shurain** [comment]
I encountered a similar problem. Could fix it by adding `x-notion-active-user-header` to the header.
