### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by misha-tgshv** [wrjlewis/notion-search-alfred-workflow#25]
Is it possible in the future to open url (property) that is specified inside pages? Or use search in other fields of the database.

For example, I use Notion as a bookmark manager and sometimes it is more convenient to immediately open an external url so as not to go to a page in Notion.

I would suggest adding a command key for this. By default, the page will open, and when you enter the command key, the URL inside the page would open. Something similar is implemented in [Raindrop.app](https://github.com/westerlind/alfred-raindrop-search).

**Setup**
Database Bookmarks (column url)
<img src="https://d.pr/i/IE6lzO+" alt="text" width="100%" height="100%">

Bookmark the article _How to Create Your First Relational Database_ in Notion
<img src="https://d.pr/i/vq28la+" alt="text" width="100%" height="100%">

1. Search Pages in Notion and click with key ⌘ 
<img src="https://d.pr/i/3fnE0j+" alt="text" width="100%" height="100%">

2. Open URL article in Safari
<img src="https://d.pr/i/WDxleA+" alt="text" width="100%" height="100%">

**Comment by sinewave** [comment]
+100!!

I also use Notion as a bookmark repo and would use this all day... especially with the way notion currently handles links :(

**Comment by wrjlewis** [comment]
Thanks for sharing!

I think this is a fairly specific use case of Notion and this Alfred plugin aims to be a more generic helper tool, so it's unlikely I'll implement this , but someone else can and raise a PR of course.

I would expect any implementation to be far easier once the Notion API (coming soon) is released.
