### ISSUE TITLE
Can't get it to work! 

### ISSUE THREAD

**Issue by leabers** [wrjlewis/notion-search-alfred-workflow#26]
I've tried to install this workflow but it doesn't work. 

When I use alfred to search 'ns _term I want to search_', '**no results go to homepage**' comes up, instead of successfully searching through Notion. 
I have set isNagivableOnly to false and useDesktopClient to true. I have inserted the cookie and space Id values into alfred. 

I am using version 0.3.3.

<img width="488" alt="Workflow environmental variables" src="https://user-images.githubusercontent.com/74153021/98847503-a4744900-2450-11eb-8cb6-3983cd484825.png">

<img width="714" alt="Debug info" src="https://user-images.githubusercontent.com/74153021/98847493-a2aa8580-2450-11eb-8da7-ad56709d7d41.png">
<img width="529" alt="The Problem" src="https://user-images.githubusercontent.com/74153021/98847498-a3dbb280-2450-11eb-8bb3-fd161ab51140.png">

**Comment by wrjlewis** [comment]
Hey

This may be a known issue.

"Known issue: Some users have experienced issues with copying these values directly from developer tools, but have seen success by copying and pasting the values into TextEdit or a different text editor first, this probably "strips out" or removes any problematic formatting."

Have you tried copying and pasting the cookie and space id into a text editor first, eg TextEdit, then copying from there into Alfred?

**Comment by leabers** [comment]
I have tried that, but it still isn't working for me..

**Comment by wrjlewis** [comment]
Have you tried logging out and logging back into Notion, then copying the updated information from developer tools? The Notion public API will be out soon which will mean you'll be able to login properly through the alfred app in future 🙌

**Comment by wrjlewis** [comment]
I'm going to close this issue now
