### ISSUE TITLE
Option to match title only

### ISSUE THREAD

**Issue by chrisgrieser** [wrjlewis/notion-search-alfred-workflow#33]
**Is your feature request related to a problem? Please describe.**
removes noise from the search results (I think?). Potentially speeds ups the search a bit (I think?)

**Describe the solution you'd like**
an option, e.g. as a workflow environment variable, to search only the title. Like when you use quicksearch and check the filter "only match titles"

**Describe alternatives you've considered**
Alternatives would be to use the Notion App/Website itself, but obviously, we want to use Alfred. :)

**Comment by wrjlewis** [comment]
Hey!

Thanks for the request. I actually have this functionality built in already I believe.. though its not entirely obvious. 

You can set the workflow variable 'isNavigableOnly' to true, and this produces the exact same request as "only match titles". 'isNavigableOnly' is the terminology Notion use on the backend.  

Try it out and see if it does what you expect?

**Comment by chrisgrieser** [comment]
ah, I see, got it, thanks!
