### ISSUE TITLE
Possible to show most recent pages when triggering the workflow?

### ISSUE THREAD

**Issue by sinewave** [wrjlewis/notion-search-alfred-workflow#35]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would be great to be able to see the most recently viewed pages when first invoking the workflow similar to how quick search works in Notion.

**Additional context**
I often find that trying to remember the keyword to search slows things down when instead I know it was a page I was just working on.

**Comment by wrjlewis** [comment]
Thanks for the suggestion. I have implemented this in the latest release 🚀 @sinewave
