### ISSUE TITLE
Probably not a bug - but I've been trying to make this work for 4 hours

### ISSUE THREAD

**Issue by danMulligan** [wrjlewis/notion-search-alfred-workflow#41]
the closest thing I could find resembling a "**notionSpaceId**" was at the bottom of the "**x-notion-active-user-header**" at the bottom of the Request Headers - in Firefox - I started in Chrome, then Safari... sorry, no clue about API whatsoever. 

Four hours of trial and error later, here's the bug report: 

[00:31:25.633] Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.E292BE38-2E96-4138-8C64-ED4BE396AEAF%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Queuing argument ''
[00:31:25.711] Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.E292BE38-2E96-4138-8C64-ED4BE396AEAF%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Script with argv '(null)' finished
[00:31:25.717] ERROR: Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.E292BE38-2E96-4138-8C64-ED4BE396AEAF%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Code 127: /bin/bash: python3: command not found

please advise, this has broken me.
thanks, 
Dan

**Comment by wrjlewis** [comment]
Hey

The error indicates that python3 isn't installed on your system, and it's required by the workflow.

When you tried running the workflow, it should have come up with a prompt to install developer tools (which includes python3), does that happen? 

If not, try opening terminal, an application that can be found in 'Applications' within finder. Type  
xcode-select --install
and press enter. This should trigger the prompt that asks you to install developer tools.

In regards to the spaceId. In chrome you can find it as seen in the screenshot below, you'll see 'search' on the left hand side, this will be there and selectable if you try a notion quick search, while you've got the developer window open. Then you can find the spaceId in the request payload area. 

![image](https://user-images.githubusercontent.com/1543626/155835189-29ec8bac-8595-4fe0-8282-36441490fd83.jpeg)

**Comment by danMulligan** [comment]
Hi Will, thanks for replying. I didn't realise it needed Python 3. 

I'm running Hi Sierra still so I followed a [tutorial](https://www.youtube.com/watch?v=6Vm1N28KOLo&t=626s) for that. And ended up building a whole python "environment" or something ala Homebrew, Xcode et al.

I can't work out how to make it default to Python 3 instead of the pre-installed v2.7...
Redirect the v3 directory to the top of the path. Something to do with Bash... [here](https://youtu.be/6Vm1N28KOLo?t=612)

I'm gonna have to take the long view on solving this. I have other life priorities atm :/ thanks for getting in touch

**Comment by wrjlewis** [comment]
> I can't work out how to make it default to Python 3 instead of the pre-installed v2.7...

The workflow automatically runs python3, so you don't need to do anything else on this. It's hardcoded into the workflow to run the python3 command.

Did you try 'xcode-select --install' in the terminal?

Thanks

**Comment by danMulligan** [comment]
![Screen Shot 2022-02-26 at 20 41 22](https://user-images.githubusercontent.com/100414621/156588959-4058ef4a-a369-4bb3-8ad7-2f6a8fffd11f.png)
![Screen Shot 2022-02-26 at 21 46 49](https://user-images.githubusercontent.com/100414621/156588963-7ad1a86d-6af3-4996-bc41-b2d43bcc09a6.png)
![Screen Shot 2022-02-26 at 22 22 16](https://user-images.githubusercontent.com/100414621/156588966-74887b54-d07c-44af-8354-2dbdadaff129.png)
![Screen Shot 2022-03-03 at 14 44 23](https://user-images.githubusercontent.com/100414621/156588968-05ca5236-4828-475e-9c2d-bdcbd7362314.png)

Hi Will, I got as far as installing Python 3 via https://www.python.org/download/releases/3.0/
That didn't get me far. Because Terminal kept saying it was running 2.7 still

After that I resorted to the whole "build" thing ala that guys video. So I installed homebrew, xcode9, CommandLineTools and Python directly within Terminal.

Still couldn't get it to over ride v2.7 
Still got nowhere within Alfred...

**Comment by danMulligan** [comment]
![Screen Shot 2022-03-03 at 15 13 21](https://user-images.githubusercontent.com/100414621/156593489-9f48de4d-6e16-4932-ab9c-44f15d1073d0.png)
![Screen Shot 2022-03-03 at 15 12 45](https://user-images.githubusercontent.com/100414621/156593506-500d1f1b-dda8-4223-b579-a34d1eb88d0a.png)
![Screen Shot 2022-03-03 at 15 12 10](https://user-images.githubusercontent.com/100414621/156593509-64d6af39-2398-4ab8-9c2d-932a2d1be210.png)
![Screen Shot 2022-03-03 at 15 11 45](https://user-images.githubusercontent.com/100414621/156593511-d1ee33d9-7b76-4e55-b3e5-2380122bf389.png)


Here's me trying again to reinstall the NotionSearch workflow, adding the cookies and cream, and falling over. Any tips? Much obliged :)

**Comment by wrjlewis** [comment]
I deleted your previous message with the screenshots in case it contained sensitive information (token and cookie..)

When you run `python` you explicitly tell the terminal to run python 2. My workflow uses the command `python3` which will run python3. So if you were to type `python3` into your terminal, you'll find you won't see any reference to python 2.7, and probably you've installed python3 perfectly well. 

For some reason Alfred isn't finding python3 in the right place, I suspect. 

This is a bit of a hack that should get it working, based on what you've said:

Open Alred Preferences, click on the notion workflow, double click on the script filter box (with the notion icon), under 'script' replace python3 with /usr/local/bin/python3 so it looks like this:
`/usr/local/bin/python3 notion.py "{query}"`

**Comment by danMulligan** [comment]
Hi Will, many thanks... nearly there. After adding the hack it's the first time the search bar / keyword has resulted in the NS icon appearing! Unfortunately the search itself was a disaster... 

What does all this mean do you recon? Incorrectly configured? 
(This is the abridged version repeating the same "error notion search" and "SSL certificate failure")

Thanks for the assistance!

[16:57:05.440] Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.253436AD-178C-43F6-880E-837FB84B361D%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Queuing argument 'a'
[16:57:05.592] Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.253436AD-178C-43F6-880E-837FB84B361D%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Queuing argument 'ac'
[16:57:05.679] Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.253436AD-178C-43F6-880E-837FB84B361D%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Script with argv '(null)' finished
[16:57:05.683] ERROR: Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.253436AD-178C-43F6-880E-837FB84B361D%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Code 1: Traceback (most recent call last):
  File "/Users/imac-2011/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.253436AD-178C-43F6-880E-837FB84B361D/notion.py", line 216, in <module>
    conn.request("POST", "/api/v3/search",
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1034, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 974, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1448, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

![Screen Shot 2022-03-03 at 16 57 30](https://user-images.githubusercontent.com/100414621/156614341-daa994ff-6a83-42d1-be77-0ef0a6807a35.png)

**Comment by wrjlewis** [comment]
Hmmmm, I'm not familiar with this error, something to do with the different way you've installed Python perhaps but I would suggest trying this, which came up when I googled the [solution](https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate):

![image](https://user-images.githubusercontent.com/1543626/156628137-8115258c-df20-45a7-8854-ce3d1ad0b3f7.png)

^ Can you find that same Python folder, within your Applications folder? If so double click the highlighted Install Certificates file, and you should be good from then on.

**Comment by danMulligan** [comment]
It's Alive! Thank you so much Will! The SSL certificate has made all the difference. I can't believe it. The ability to trawl through and immediately access anything within my Notion. That's a very noble gift you've given to humanity. I sponsored you ten bucks$ for your help today. Really appreciated the guidance. 

thanks
Dan

**Comment by wrjlewis** [comment]
> It's Alive! Thank you so much Will! The SSL certificate has made all the difference. I can't believe it. The ability to trawl through and immediately access anything within my Notion. That's a very noble gift you've given to humanity. I sponsored you ten bucks$ for your help today. Really appreciated the guidance. 
> 
> 
> 
> thanks
> 
> Dan

More than welcome and thank you very much, I really appreciate it. I'm very glad it's working and we persevered to get to the good result 🙌. Thanks for you support. 

If I ever update the workflow and it stops working again for you, the only step you'd need to do again is the bit where you updated python3 to /usr/local/...

**Comment by bymilano** [comment]
Hey Will, I followed all the steps but I'm still unable to use the workflow because I get this every time I search for something:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/101039151/156915326-8aa7c6e1-0954-479c-94cb-a26b669627cf.png">

Here is the bug report from running that test if that helps:

[18:30:16.471] Logging Started...
[18:30:18.771] Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.CC26B614-4DF9-46AE-859A-E94BAD011914%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Queuing argument ''
[18:30:18.840] Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.CC26B614-4DF9-46AE-859A-E94BAD011914%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Script with argv '(null)' finished
[18:30:18.843] Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.CC26B614-4DF9-46AE-859A-E94BAD011914%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] {"items": [{"uid": 1, "type": "default", "title": "Open Notion - No results, empty query, or error", "arg": "notion://www.notion.so/"}]}
[18:30:19.008] Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.CC26B614-4DF9-46AE-859A-E94BAD011914%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Queuing argument 't'
[18:30:19.159] Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.CC26B614-4DF9-46AE-859A-E94BAD011914%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Queuing argument 'te'
[18:30:19.320] Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.CC26B614-4DF9-46AE-859A-E94BAD011914%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Queuing argument 'tes'
[18:30:19.484] Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.CC26B614-4DF9-46AE-859A-E94BAD011914%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Queuing argument 'test'
[18:30:19.754] Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.CC26B614-4DF9-46AE-859A-E94BAD011914%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Script with argv '(null)' finished
[18:30:19.760] Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.CC26B614-4DF9-46AE-859A-E94BAD011914%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] {"items": [{"uid": 1, "type": "default", "title": "Open Notion - No results, empty query, or error", "arg": "notion://www.notion.so/"}]}

Please let me know if you have any ideas on why this is happening!

**Comment by danMulligan** [comment]
hi Will, sorry to be the bearer of bad news... Do you know the issue where it appears to be working but it only ever finds the same page over and over...? Something's over-riding the actual page I've asked to visit. Like it's assigned a homepage and keeps sending me to there.

**Comment by wrjlewis** [comment]
> hi Will, sorry to be the bearer of bad news... Do you know the issue where it appears to be working but it only ever finds the same page over and over...? Something's over-riding the actual page I've asked to visit. Like it's assigned a homepage and keeps sending me to there.

That is bizarre... is it still happening? 

Just to check, have you tried updating the token (by copying and pasting it again)?

**Comment by wrjlewis** [comment]
> Hey Will, I followed all the steps but I'm still unable to use the workflow because I get this every time I search for something:
> 
> <img alt="image" width="500" src="https://user-images.githubusercontent.com/101039151/156915326-8aa7c6e1-0954-479c-94cb-a26b669627cf.png">
> 
> Here is the bug report from running that test if that helps:
> 
> [18:30:16.471] Logging Started... [18:30:18.771] Notion Search[Script Filter] Queuing argument '' [18:30:18.840] Notion Search[Script Filter] Script with argv '(null)' finished [18:30:18.843] Notion Search[Script Filter] {"items": [{"uid": 1, "type": "default", "title": "Open Notion - No results, empty query, or error", "arg": "notion://www.notion.so/"}]} [18:30:19.008] Notion Search[Script Filter] Queuing argument 't' [18:30:19.159] Notion Search[Script Filter] Queuing argument 'te' [18:30:19.320] Notion Search[Script Filter] Queuing argument 'tes' [18:30:19.484] Notion Search[Script Filter] Queuing argument 'test' [18:30:19.754] Notion Search[Script Filter] Script with argv '(null)' finished [18:30:19.760] Notion Search[Script Filter] {"items": [{"uid": 1, "type": "default", "title": "Open Notion - No results, empty query, or error", "arg": "notion://www.notion.so/"}]}
> 
> Please let me know if you have any ideas on why this is happening!

Not sure why this wouldn't be working, though sometimes refreshing the token, by copying and pasting it, seems to fix things! Have you tried that? Is it still happening?

There are few issues cropping up with the workflow change to Python3 and the new Mac OS removing python2, that could be linked to some of these errors. To be sure I will need to add proper error logging to the workflow, one for the to-do list one of these weekends.

**Comment by bymilano** [comment]
I just copy and pasted the spaceID and it works now! For some reason, when I had the issue originally, copy and pasting did not make any difference but hey, I'm not complaining that it does now ahahah.

Thanks for your help Will!

**Comment by wrjlewis** [comment]
Haha brilliant, fingers crossed it stays that way 😄 glad it’s working

**Comment by wrjlewis** [comment]
Is anyone still experiencing issues, after having the latets mac and alfred updates, and after updating the cookie?
I would also suggest trying setting the showRecentlyViewedPages env variable to false, to see if that helps.

**Comment by persusc** [comment]
Hi Will, I'm sorry to bother you but I also have the same Code 1 Error. I have installed the certificate and it shows this.

[11:58:25.227] Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.88A79C70-7EFD-475B-84F5-22A6862DA869%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Queuing argument 'dsfsdfsdfsdf'
[11:58:25.299] Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.88A79C70-7EFD-475B-84F5-22A6862DA869%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Script with argv 'dsfsdfsdfsdf' finished
[11:58:25.306] ERROR: Notion Search[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.88A79C70-7EFD-475B-84F5-22A6862DA869%3E7DD3BDE5-A157-42E5-9376-F681FB50A4EE)] Code 1: Traceback (most recent call last):
  File "notion.py", line 216, in <module>
    conn.request("POST", "/api/v3/search",
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1293, in _send_request
    self.putheader(hdr, value)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'notion_browser_id=fa800413-a809-4864-a34e-eedea288f354; NEXT_LOCALE=en-US; intercom-id-gpfdrxfd=c1983e72-5979-4e92-bae4-13d366e9ef68; ajs_user_id=cd2e6d1225074e6f91461552d79c38a6; ajs_group_id=010ce9291e4e479cb49ab2c2cb221836; notion_check_cookie_consent=false; logglytrackingsession=5291bbb0-5225-4383-915b-86c3812a7916; notion_experiment_device_id=06f6756b-7255-4890-9cfa-e656647f62eb; notion_locale=en-US/autodetect; _gcl_aw=GCL.1650596207.Cj0KCQjwgYSTBhDKARIsAB8Kukuf5Bc5HuIhs3sXqjRMOBYUntb5Sh_H-qskoxmBpXbVBLlnCL_5ZmgaAlzMEALw_wcB; _gcl_au=1.1.673351018.1650596207; mutiny.user.session_number=1; mutiny.user.token=eee2992e-2042-44f3-957a-bfca63db42b0; mutiny.user.session=d9ec711a-3df6-4e83-a082-fd99428af601; _ga=GA1.1.1145027696.1650596207; _mkto_trk=id:414-XMY-838&token:_mch-www.notion.so-1650596207213-33916; ajs_anonymous_id=fa800413a8094864a34eeedea288f354; cb_user_id=null; cb_group_id=null; cb_anonymous_id=%22249ca9a0-a310-47fb-b6b8-53fd873c3c3e%22; _ga_9ZJ8CB186L=GS1.1.1650596206.1.1.1650596208.0; csrf=af46ac47-6258-49e7-b050-6eac2f27ef11; token_v2=8f2a93a4f6e4d466655a629e75cb366ab1d794a3692e2d0d2372165052e4e21d7ffc419308156bc166efb30d34090064fc0131f8b8baa9476518d8d4328a871f0f1254dccbdd368e6ba42980bc33; notion_user_id=cd2e6d12-2507-4e6f-9146-1552d79c38a6; notion_users=[%22cd2e6d12-2507-4e6f-9146-1552d79c38a6%22]; intercom-session-gpfdrxfd=ZjVoeDU3bmJIZ2xPb0dJbzNjK2k5RzFEM3AxTllFRHp5Rmd4amUvR3MzMFg0Mjg4WUdwZy9INmU0eXdSdWFSNi0tNFFPWXpyRzdxblZkN0JsOTVNTUJOQT09--7a30de44022743a152a811134e8b2e1fab66d9b7; amp_af43d4=fa800413a8094864a34eeedea288f354.Y2QyZTZkMTIyNTA3NGU2ZjkxNDYxNTUyZDc5YzM4YTY=..1g17j6mij.1g17jbjqt.2g.7.2n\n notion_browser_id=fa800413-a809-4864-a34e-eedea288f354; NEXT_LOCALE=en-US; intercom-id-gpfdrxfd=c1983e72-5979-4e92-bae4-13d366e9ef68; ajs_user_id=cd2e6d1225074e6f91461552d79c38a6; ajs_group_id=010ce9291e4e479cb49ab2c2cb221836; notion_check_cookie_consent=false; logglytrackingsession=5291bbb0-5225-4383-915b-86c3812a7916; notion_experiment_device_id=06f6756b-7255-4890-9cfa-e656647f62eb; notion_locale=en-US/autodetect; _gcl_aw=GCL.1650596207.Cj0KCQjwgYSTBhDKARIsAB8Kukuf5Bc5HuIhs3sXqjRMOBYUntb5Sh_H-qskoxmBpXbVBLlnCL_5ZmgaAlzMEALw_wcB; _gcl_au=1.1.673351018.1650596207; mutiny.user.session_number=1; mutiny.user.token=eee2992e-2042-44f3-957a-bfca63db42b0; mutiny.user.session=d9ec711a-3df6-4e83-a082-fd99428af601; _ga=GA1.1.1145027696.1650596207; _mkto_trk=id:414-XMY-838&token:_mch-www.notion.so-1650596207213-33916; ajs_anonymous_id=fa800413a8094864a34eeedea288f354; cb_user_id=null; cb_group_id=null; cb_anonymous_id=%22249ca9a0-a310-47fb-b6b8-53fd873c3c3e%22; _ga_9ZJ8CB186L=GS1.1.1650596206.1.1.1650596208.0; csrf=af46ac47-6258-49e7-b050-6eac2f27ef11; token_v2=8f2a93a4f6e4d466655a629e75cb366ab1d794a3692e2d0d2372165052e4e21d7ffc419308156bc166efb30d34090064fc0131f8b8baa9476518d8d4328a871f0f1254dccbdd368e6ba42980bc33; notion_user_id=cd2e6d12-2507-4e6f-9146-1552d79c38a6; notion_users=[%22cd2e6d12-2507-4e6f-9146-1552d79c38a6%22]; intercom-session-gpfdrxfd=ZjVoeDU3bmJIZ2xPb0dJbzNjK2k5RzFEM3AxTllFRHp5Rmd4amUvR3MzMFg0Mjg4WUdwZy9INmU0eXdSdWFSNi0tNFFPWXpyRzdxblZkN0JsOTVNTUJOQT09--7a30de44022743a152a811134e8b2e1fab66d9b7; amp_af43d4=fa800413a8094864a34eeedea288f354.Y2QyZTZkMTIyNTA3NGU2ZjkxNDYxNTUyZDc5YzM4YTY=..1g17j6mij.1g17jbjqt.2g.7.2n\nnotion_browser_id=fa800413-a809-4864-a34e-eedea288f354; NEXT_LOCALE=en-US; intercom-id-gpfdrxfd=c1983e72-5979-4e92-bae4-13d366e9ef68; ajs_user_id=cd2e6d1225074e6f91461552d79c38a6; ajs_group_id=010ce9291e4e479cb49ab2c2cb221836; notion_check_cookie_consent=false; logglytrackingsession=5291bbb0-5225-4383-915b-86c3812a7916; notion_experiment_device_id=06f6756b-7255-4890-9cfa-e656647f62eb; notion_locale=en-US/autodetect; _gcl_aw=GCL.1650596207.Cj0KCQjwgYSTBhDKARIsAB8Kukuf5Bc5HuIhs3sXqjRMOBYUntb5Sh_H-qskoxmBpXbVBLlnCL_5ZmgaAlzMEALw_wcB; _gcl_au=1.1.673351018.1650596207; mutiny.user.session_number=1; mutiny.user.token=eee2992e-2042-44f3-957a-bfca63db42b0; mutiny.user.session=d9ec711a-3df6-4e83-a082-fd99428af601; _ga=GA1.1.1145027696.1650596207; _mkto_trk=id:414-XMY-838&token:_mch-www.notion.so-1650596207213-33916; ajs_anonymous_id=fa800413a8094864a34eeedea288f354; cb_user_id=null; cb_group_id=null; cb_anonymous_id="249ca9a0-a310-47fb-b6b8-53fd873c3c3e"; _ga_9ZJ8CB186L=GS1.1.1650596206.1.1.1650596208.0; csrf=af46ac47-6258-49e7-b050-6eac2f27ef11; token_v2=8f2a93a4f6e4d466655a629e75cb366ab1d794a3692e2d0d2372165052e4e21d7ffc419308156bc166efb30d34090064fc0131f8b8baa9476518d8d4328a871f0f1254dccbdd368e6ba42980bc33; notion_user_id=cd2e6d12-2507-4e6f-9146-1552d79c38a6; notion_users=["cd2e6d12-2507-4e6f-9146-1552d79c38a6"]; intercom-session-gpfdrxfd=ZjVoeDU3bmJIZ2xPb0dJbzNjK2k5RzFEM3AxTllFRHp5Rmd4amUvR3MzMFg0Mjg4WUdwZy9INmU0eXdSdWFSNi0tNFFPWXpyRzdxblZkN0JsOTVNTUJOQT09--7a30de44022743a152a811134e8b2e1fab66d9b7; amp_af43d4=fa800413a8094864a34eeedea288f354.Y2QyZTZkMTIyNTA3NGU2ZjkxNDYxNTUyZDc5YzM4YTY=..1g17j6mij.1g17jbjqt.2g.7.2n'

I've tried trouble shooting for a while but unfortunately I don't think I am too familiar with coding. Can you please help me? Thanks a lot man.

**Comment by persusc** [comment]
> Hey Will, I followed all the steps but I'm still unable to use the workflow because I get this every time I search for something:
> 
> <img alt="image" width="500" src="https://user-images.githubusercontent.com/101039151/156915326-8aa7c6e1-0954-479c-94cb-a26b669627cf.png">
> 
> Here is the bug report from running that test if that helps:
> 
> [18:30:16.471] Logging Started... [18:30:18.771] Notion Search[Script Filter] Queuing argument '' [18:30:18.840] Notion Search[Script Filter] Script with argv '(null)' finished [18:30:18.843] Notion Search[Script Filter] {"items": [{"uid": 1, "type": "default", "title": "Open Notion - No results, empty query, or error", "arg": "notion://www.notion.so/"}]} [18:30:19.008] Notion Search[Script Filter] Queuing argument 't' [18:30:19.159] Notion Search[Script Filter] Queuing argument 'te' [18:30:19.320] Notion Search[Script Filter] Queuing argument 'tes' [18:30:19.484] Notion Search[Script Filter] Queuing argument 'test' [18:30:19.754] Notion Search[Script Filter] Script with argv '(null)' finished [18:30:19.760] Notion Search[Script Filter] {"items": [{"uid": 1, "type": "default", "title": "Open Notion - No results, empty query, or error", "arg": "notion://www.notion.so/"}]}
> 
> Please let me know if you have any ideas on why this is happening!

Hi Will, I've also encountered this issue and tried to copy and paste both the values and it still doesn't work. I've updated the cookie and I've also tried setting the showRecentlyViewedPages env variable to false and it doesn't work either. Can you please help me? Thanks a lot man

**Comment by Lishuoyy** [comment]
Hello, I can use Alfred to search for content in notion, but the search results are only displayed for a second, and then disappear quickly and become No results, as shown in the following figure.

![](https://user-images.githubusercontent.com/101039151/156915326-8aa7c6e1-0954-479c-94cb-a26b669627cf.png)
The debug information on which I run the test is as follows, how to solve it? 
I hope you can reply me. Thank you.
![image](https://user-images.githubusercontent.com/66720796/164882636-2bf75a60-ce6d-415c-8aa6-78e090bda8b9.png)

**Comment by eshchris** [comment]
This likely isn't the issue others are facing but I was stuck for a while with the same error. Then I copied my cookie value and pasted it in Text Edit and discovered it was duplicated (I'd pasted it twice). So if anyone else is getting the No Results error, start by double-checking your cookie and SpaceID

**Comment by wrjlewis** [comment]
I'm going to close this issue as its been a while and there are potentially multiple issues here, if they are still being experienced. Please raise a new issue, if thats the case.
