### ISSUE TITLE
Add full-text search support

### ISSUE THREAD

**Issue by alimov-andrey** [wrjlewis/notion-search-alfred-workflow#44]
It would be great to add word search support. So that, for example, the phrase "three black crows" finds the whole article

**Comment by wrjlewis** [comment]
I don't understand what this means. Can you give some examples of how this differs to current functionality?

**Comment by alimov-andrey** [comment]
Let's say I want to find an article that I saved in notion by a phrase that is present in the text. So I type the phrase "morning star" and I get a link to an article on japanese candlestick charting techniques

**Comment by wrjlewis** [comment]
Have you tried setting 'isNavigableOnly' to false in the env variables?

**Comment by alimov-andrey** [comment]
Sorry, I must have missed it. The question is closed.  Thank you for your help.
