### ISSUE TITLE
Does it work with notion-enhancer desktop? 

### ISSUE THREAD

**Issue by viv-yeung** [wrjlewis/notion-search-alfred-workflow#49]
I use notion enhancer and it seems to be incompatible with the workflow. The pages I search for will show up in Alfred. When I press enter it will re-direct me to notion enhancer but will not load the page. Does anyone know how to get around this?

Thanks anyway!

**Comment by wrjlewis** [comment]
Hi

Are you using notion enhancer, as the chrome/firefox extension or the desktop app? 

Ultimately, Alfred just opens a URL so it shouldn't be incompatible by design.

**Comment by viv-yeung** [comment]
Thanks for getting back to me! Turns out it was a safari issue, silly me. The workflow now works flawlessly. Thanks so much!

**Comment by wrjlewis** [comment]
Awesome
