### ISSUE TITLE
Possible search API specification change

### ISSUE THREAD

**Issue by amrael** [wrjlewis/notion-search-alfred-workflow#50]
**Before reporting the issue, did you ?**
- [x] Update your `notionSpaceId` and `cookie` value in Alfred Settings. If you don't know how to do this, [check this](https://github.com/wrjlewis/notion-search-alfred-workflow#workflow-variables)

**Describe the bug**
I noticed that the workflow stopped working with a {query} argument a couple of days ago. I assume notion.py may need to be changed in accordance with the new search API spec.

**Screenshots**
![image](https://user-images.githubusercontent.com/7359540/182755474-5e8ad590-9c05-4993-b1ba-198413e0a4ae.png)
![image](https://user-images.githubusercontent.com/7359540/182755168-152a0fe4-c846-4109-a98f-0431da459fe0.png)

**Workflow (please complete the following information):**
 - Version
 0.4.1

**Comment by iamstevendao** [comment]
same issue 👍🏻

**Comment by wrjlewis** [comment]
I'm actually on holiday for a while so it will take me a week to look at this issue. But sounds like an api change, hopefully a minor one.

**Comment by maryam-mahla** [comment]
Same issue on my side, following the thread closely for update, thank you !

**Comment by amrael** [comment]
I just got it working again with the changes I made in PR #53

**Comment by mvaneijgen** [comment]
Just add the hot fix by @amrael and it works!

Go to "Show Alfred Preferences" -> Workflows -> Right click "Notion Search" show in finder -> Open `notion.py` in a code editor.

Then replace the code with the below version
https://github.com/amrael/notion-search-alfred-workflow/blob/hotfix/search-api/notion.py

Or wait for @wrjlewis to push an update.

**Comment by wrjlewis** [comment]
This has been fixed with [v0.4.2](https://github.com/wrjlewis/notion-search-alfred-workflow/releases/download/v0.4.2/Notion.Search.alfredworkflow)
