### ISSUE TITLE
Run Script is not running

### ISSUE THREAD

**Issue by day0n** [wrjlewis/notion-search-alfred-workflow#60]
When I searched with ns, there was no result. Through debug, I found that Run Script did not seem to be started.
Linux appears many times in my notes.
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/72638802/194104987-14bc7b8e-94e8-4c6e-bc4d-9609a1cb5145.png">

**Comment by wrjlewis** [comment]
Hi

Can you please update to the latest version 0.4.3.

Also suggest updating your cookie and spaceId as often this can fix issues.

Finally if it's still not working please post a screenshot of the pop up Alfred search showing no results. 

Thanks

**Comment by day0n** [comment]
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/72638802/194288713-d9568ac5-b8b5-4adc-b954-aea6d67ef88d.png">

**Comment by day0n** [comment]
<img width="726" alt="image" src="https://user-images.githubusercontent.com/72638802/194288826-ea663553-81d5-4fcd-9a03-0be4c639c06b.png">

**Comment by day0n** [comment]
It still does not work.

**Comment by wrjlewis** [comment]
Hmm, looks like the request is working to a certain point but there is not results object being returned, I'm not sure why that is. 

I see you have an Alfred update pending too, I don't think that will fix the error but it would be worth ruling that out.

**Comment by day0n** [comment]
Update doesn't work.My notion uses a desktop client, do I also need to update cookie and spaceId?

**Comment by wrjlewis** [comment]
Yes you will still need to update the cookie and spaceid, which is stored within the workflow itself, and the fact you are using the desktop version is irrelevant to that. You will also need to set the 'useDesktopClient' flag to true. 
Why does the update not work?

**Comment by day0n** [comment]
The problem has been solved. Thank you very much for your help.

**Comment by day0n** [comment]
If I use a desktop client, do I also need to update the values of cookies
and spaceId?

Will Lewis ***@***.***> 于2022年10月6日周四 00:06写道：

**Comment by wrjlewis** [comment]
Yes you do
