### ISSUE TITLE
search by text

### ISSUE THREAD

**Issue by day0n** [wrjlewis/notion-search-alfred-workflow#61]
Using search in notion, you can directly search for relevant keywords, even if keywords can be searched in the article, but it seems that you can only search for the title of the article with this workflow at present, but it can't match the content of the article. I hope this function can be added. Maybe this can directly call the search interface in note?

**Comment by wrjlewis** [comment]
Hello

You should be able to search for keywords within pages too. To do this, ensure that 'isNavigableOnly' is set to False. 

Thanks, Will.

**Comment by day0n** [comment]
wow, This is very helpful to me. This is the best workflow in the world!
