### ISSUE TITLE
Notion SVG icons are not displayed

### ISSUE THREAD

**Issue by epitonium** [wrjlewis/notion-search-alfred-workflow#62]
Notion now supports svg icons for your pages and as it seems Alfred supports only image formats, so instead of displaying page icons in the search there is a default Notion logo presented.

![CleanShot 2022-10-06 at 19 43 42@2x](https://user-images.githubusercontent.com/6273817/194371578-c17e78e3-c407-4b7b-ac59-9414c0210166.jpg)

![CleanShot 2022-10-06 at 19 45 25@2x](https://user-images.githubusercontent.com/6273817/194371592-4db89853-25cb-4d7a-a23a-6e7fc661c5df.jpg)

**Comment by wrjlewis** [comment]
Hi @epitonium 

You're absolutely right, and whilst the workflow has the ability to download and process SVG images, the Alfred software does not support SVG images as icons. 

So I don't believe we can solve this one until Alfred supports SVG icons. 

Thanks

**Comment by epitonium** [comment]
Perhaps some type of "ImageMagick" tool (if installed) could be used to convert downloaded SVGs to an image format supported by Alfred, named by its URL and stored inside the workflow's local folder? So later it could be restored by name if exists.

**Comment by wrjlewis** [comment]
Yes, I think converting from SVG to something else using a third party library would be the only thing we can do for now. 
I have so far avoided the use of third party libraries to not create additional install steps for folk, some of which are not adept with terminal or Python.

**Comment by epitonium** [comment]
You could run conversion implementation for SVGs inside your scripts only after a check for those users who already have it installed. And to mention inside README file that those users having problems with SVG icons need to proceed to an extra step installing `ImageMagick` on their system using DMG package from the official site or using `Homebrew` executing `brew install imagemagick` in terminal for example 😃. With this approach third party library like `ImageMagick` would not be required by the workflow but simply serve as a troubleshooter 😃.

**Comment by wrjlewis** [comment]
Thanks @epitonium , I thikn you're spot on here and that would a good solution. 
I'm not sure when I'd get around to updating the workflow, but I'll add to the to-do list 👍

**Comment by wrjlewis** [comment]
I'm working on this, should be out in the next couple of weeks

**Comment by epitonium** [comment]
That's great! 😃
