### ISSUE TITLE
Breadcrumb Separator

### ISSUE THREAD

**Issue by christianmagill** [wrjlewis/notion-search-alfred-workflow#63]
I'd love to see a separator for the breadcrumbs under a search result.

Currently, I'm only seeing spaces in between the pages in the hierarchy, which gets confusing when there are spaces in the page names.

So Instead of:

Business Knowledge Article Name

The breadcrumbs would read as

Business > Knowledge > Article Name

Love the Workflow! Much thanks.

**Comment by wrjlewis** [comment]
Hi, 

This would be fantastic I agree, I looked into this when I was first writing this workflow, unfortunately there is any information from Notions side that would enable this feature. The data we get back is literally as displayed and it's impossible to tell which are pages within the string of words. 

Thanks
