### ISSUE TITLE
"notion search option"  disappears from Alfred

### ISSUE THREAD

**Issue by hongxunming** [wrjlewis/notion-search-alfred-workflow#67]
**Describe the bug**

Video attached below.
It seems that notion search option has disappeared from Alfred since I installed the MacOS 13 several days ago.
 (I'am not sure whether the issue is caused by the system update,  but the workflows can work weeks ago.)

**Expected behaviour**

**Screenshots**
https://user-images.githubusercontent.com/43163254/200157671-c9ceb062-f440-483a-b9a9-a0fa80cbb9b7.mp4

**Workflow**
 - Version [e.g. 0.4.3]

MacBook Air (M1 2020); macOS-Version 13.0

**Comment by hongxunming** [comment]
Hello, the issue has been fixed by changing "/bin/bash" to "/bin/zsh"...😂

<img width="519" alt="image" src="https://user-images.githubusercontent.com/43163254/200159244-e225e554-c848-4bc0-b186-1b275ccb9a16.png">

**Comment by wrjlewis** [comment]
@PolarisPolaris I would be super interested to see what the log output is, from Alfred, when you search using /bin/bash/...
Hoping that would shed light on what has happened to bash in macOS 13
