### ISSUE TITLE
"Payload" object has no attribute "pages"

### ISSUE THREAD

**Issue by roberdorfer** [wrjlewis/notion-search-alfred-workflow#74]
I get this error everytime I type "ns" to use the alfred workflow. It used to work until two weeks ago or so.

Any way to fix this? Thanks!

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/6862450/209970281-37817b1a-4836-4ce8-8688-c6d9a072d797.png">

**Comment by wrjlewis** [comment]
I can't recreate this error myself. But I would try updating your cookie and space id, you'd be amazed how many times this fixes any issues. 

I would also be interested to see what error, if any, is displayed when you try typing something eg 'ns something'. There are two different calls that are made depending on whether a query is given or not

**Comment by roberdorfer** [comment]
Hey @wrjlewis appreciate the answer.

The result of entering a search term is this:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/6862450/210442841-f5f7914e-c58d-4971-83cd-d8251ecc799a.png">

I have updated the cookie info which has solved the problem. Thank you!

**Comment by wrjlewis** [comment]
Awesome
