### ISSUE TITLE
Have tried all solutions discussed previously, SSL certificate issues still exist

### ISSUE THREAD

**Issue by Elodie-0117** [wrjlewis/notion-search-alfred-workflow#77]
SSL certificate error as this image below:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/126692797/227780767-197a0bc6-334c-432c-9da8-359902051533.png">

Debugger:
<img width="842" alt="image" src="https://user-images.githubusercontent.com/126692797/227781055-841db25b-fcc7-43d6-8158-293eaacfcefe.png">

Actions have done to try to solve this:
1. Run '/Applications/Python 3.11/Install Certificates.command' in terminal
<img width="568" alt="image" src="https://user-images.githubusercontent.com/126692797/227781210-7b31f7aa-d1c9-4067-ba47-da8f51401909.png">

2.  Browse to Applications/Python 3.11 and double-click Install Certificates.command
<img width="570" alt="image" src="https://user-images.githubusercontent.com/126692797/227781358-99f0a23b-8aac-4f42-99f6-1a5c4cd68ac7.png">

3. brew update and brew upgrade
<img width="538" alt="image" src="https://user-images.githubusercontent.com/126692797/227781427-052522e3-3ae5-4e73-9f70-e67025125ea2.png">
<img width="567" alt="image" src="https://user-images.githubusercontent.com/126692797/227781487-8c8d3037-2f07-4056-befa-5f9342e1db1d.png">

**Comment by wrjlewis** [comment]
Can you please post the error you are getting and details of the previous steps you have taken.

**Comment by Elodie-0117** [comment]
> Can you please post the error you are getting and details of the previous steps you have taken.

thanks, i have added more details on the error and things i have tried as the comment above.

**Comment by wrjlewis** [comment]
It looks like the install certificates command isn't working because of something to do with permissions. 

Could you run the same command to install certificated but put `sudo ` at the beginning, and see if this works? (If it doesn't please show the output)

**Comment by Elodie-0117** [comment]
> It looks like the install certificates command isn't working because of something to do with permissions.
> 
> Could you run the same command to install certificated but put `sudo ` at the beginning, and see if this works? (If it doesn't please show the output)

oh, i tried sudo and the ns search works now! thank you very much!

**Comment by wrjlewis** [comment]
Awesome, I've also updated the readme to include 'sudo ' in the command, for others.

**Comment by Elodie-0117** [comment]
> Awesome, I've also updated the readme to include 'sudo ' in the command, for others.

oh, just to offer the exact infomation, i tried sudo and then tried sudo -H, then the ns search works great now, SSL certificate issue solved!

**Comment by wrjlewis** [comment]
Ah ok so sudo -h ‘install…..’, right?

Because sudo by itself didn’t work?
