### ISSUE TITLE
The Alfred 5 download link is broken

### ISSUE THREAD

**Issue by CharlesMagnuson** [wrjlewis/notion-search-alfred-workflow#79]
The Alfred 5 download link at https://github.com/wrjlewis/notion-search-alfred-workflow is broken. The link currently points to https://github.com/wrjlewis/notion-search-alfred5-workflow/releases/latest/download/Notion.Search.Alfred.5.alfredworkflow which provides a 404 page when I navigate to it.

**Comment by wrjlewis** [comment]
Thanks for letting me know! Updated now
