### ISSUE TITLE
Search result: 'Payload' object has no attribute 'results'

### ISSUE THREAD

**Issue by johnathanz** [wrjlewis/notion-search-alfred-workflow#80]
**Describe the bug**
Can't seem to query Notion using the Workflow.

When I type `ns` a few of the recent notes will show up. Opening those are fine.

Typing any other search term comes back with: error 323 payload object has no attribute "result"

![2023-06-11 at 19 29 14](https://github.com/wrjlewis/notion-search-alfred-workflow/assets/1593039/0a3d41b7-b88a-4aa2-89b8-b88199f78a5f)

**To Reproduce**
Steps to reproduce the behaviour:
1. Clean install of Notion Search
2. Get Cookie & spaceID from web browser window where I did a search on notion.so
3. Put Cookie & spaceID into workflow
4. use `ns` to do search and I get no search result and the error

**Expected behaviour**
Expected search results to come through in the Alfred search results based on the search query I typed.

**Screenshots**

The same "weekend" search in Notion itself

![2023-06-11 at 19 39 33@2x](https://github.com/wrjlewis/notion-search-alfred-workflow/assets/1593039/ab51d33f-a2a7-4cee-ac33-4f29828b198b)

**Workflow (please complete the following information):**
latest version 0.5.2-alfred5

**Additional context**
Debug output
![2023-06-11 at 19 38 20](https://github.com/wrjlewis/notion-search-alfred-workflow/assets/1593039/9e436062-771e-442a-9812-197b02467e4f)

**Comment by roberdorfer** [comment]
I run into the exact same issue.

**Comment by wrjlewis** [comment]
https://github.com/wrjlewis/notion-search-alfred5-workflow/issues/9

**Comment by johnathanz** [comment]
cool. Thanks @wrjlewis and @rbieb the fix mentioned in the other thread totally works.
https://github.com/wrjlewis/notion-search-alfred5-workflow/issues/9#issuecomment-1588665974

Appreciate your work on this workflow @wrjlewis. Enjoy your break!

**Comment by wrjlewis** [comment]
This has been fixed now in the latest release, thanks for all your help 

https://github.com/wrjlewis/notion-search-alfred-workflow/releases/tag/v0.5.3-alfred4
