### ISSUE TITLE
WORK GR8! thanks!

### ISSUE THREAD

**Issue by viggin543** [wrjlewis/notion-search-alfred-workflow#87]
consider updating the docs and explain that the cookie value should be url decoded.
and include both key+value of the cookie 🙏

**Comment by wrjlewis** [comment]
In the instructions (which are little out of date), its copying over the whole cookie, which includes many key+values.

I'm not sure where you've been bitten by the cookie needing to be url decoded? 

Glad you're enjoying the workflow!
